//
//  constants.gr
//  CARM-Compiler
//
//  Created by Ollie Ford on 01/03/2015.
//  Copyright (c) 2015 OJFord. All rights reserved.
//

constant:
	floating_constant
|
	integer_constant
|
	enumeration_constant
|
	character_constant
;

floating_constant:
	FLOATCONSTANT
;

integer_constant:
	DECCONSTANT
|
	OCTCONSTANT
|
	HEXCONSTANT
;

enumeration_constant:
	IDENTIFIER
;

character_constant:
	CHARCONSTANT
|
	WCHARCONSTANT
;

string_literal:
	STRINGLITERAL
|
	WSTRINGLITERAL
;
