//
//  externaldefs.gr
//  CARM-Compiler
//
//  Created by Ollie Ford on 01/03/2015.
//  Copyright (c) 2015 OJFord. All rights reserved.
//

translation_unit:
	external_declaration
|
	translation_unit external_declaration
;

external_declaration:
	function_definition
|
	declaration
;

function_definition:
	declarator
|
	declaration_specifiers declarator
|
	compound_stmt
|
	declaration_list compound_stmt
;
